### ISSUE TITLE
Deleting languages

### ISSUE THREAD

**Issue by TMFnelson** [DiscipleTools/disciple-tools-webform#31]
I go into disciple tools settings/custom fields/languages... and then I try to edit the languages that are there. However I am not able to use th "Hide/Archive" column. For some reason that column has nothing in it. 

![Untitled](https://user-images.githubusercontent.com/69496473/89857088-ab7b8900-dbcd-11ea-9ba2-b41fdec3a685.png)

**Comment by corsacca** [comment]
Thanks! Here is the fix:
https://github.com/DiscipleTools/disciple-tools-theme/commit/ebd0d6bd419f16cc8e5a9990319c59ddeb76acb1
It will be available when 0.32.0 is released.
