### ISSUE TITLE
Setting base user on a webform should have user search

### ISSUE THREAD

**Issue by ahillbilly** [DiscipleTools/disciple-tools-webform#33]
There is a weird work around to find the user's user number on the front end interface, and then come back to the backend settings and enter the number and hope for the best, but it would be much better to search for the user in the base user selection field, see the username like all type-aheads on the front end (and I think in the FB plugin base user setting) and then select the user and have confidence that it is correct.

**Comment by corsacca** [comment]
It is currently just a number input:
![image](https://user-images.githubusercontent.com/24901539/114060996-d4a00680-988d-11eb-8520-5e9d91beaf2c.png)
Copy the user select from the facebook plugin: 
https://github.com/DiscipleTools/disciple-tools-facebook/blob/78daca9050a1745fe0124594bdca0b17c373578e/includes/facebook-integration.php#L330

**Comment by cwuensche** [comment]
@corsacca Is there a list of specific roles you want to select or should every user regardless of role be available for selection?

**Comment by corsacca** [comment]
@cwuensche please restrict it to the users that have the `access_contacts` capability.
