### ISSUE TITLE
translations with apostrophe's break the JS

### ISSUE THREAD

**Issue by micahmills** [DiscipleTools/disciple-tools-webform#34]
In lines the following lines (https://github.com/DiscipleTools/disciple-tools-webform/blob/1e030f3cbcb3a9182417a2a08aaa0180f9bbb5f9/public/form.php#L56-L61) if someone puts in a string with an apostrophe the JS will throw an error. The easy fix is to use `"` here instead of `'`

**Comment by corsacca** [comment]
This issue should be fixed
