### ISSUE TITLE
Missing Token

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-webform#40]
When creating a new webform the demo looks like this:
(Happens with or without a Mapbox token) 
![image](https://user-images.githubusercontent.com/24901539/114857700-7bc9f400-9de0-11eb-85ea-9f622866302b.png)

Once the "Update" button is clicked the form then appears normally
![image](https://user-images.githubusercontent.com/24901539/114858493-6ef9d000-9de1-11eb-8f51-026316453714.png)

The Demo should appear normally when creating the form.

**Comment by cwuensche** [comment]
PR opened here https://github.com/DiscipleTools/disciple-tools-webform/pull/42 @corsacca
