### ISSUE TITLE
Avoid duplicates on email and phone

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-webform#43]
Search for exact matches email and/or phone number and update the contact instead of creating a new one.

**Comment by prykon** [comment]
What if a couple shares an email address? I saw things like "peterandruthabroad@gmail.com"

**Comment by corsacca** [comment]
Good question.

**Comment by corsacca** [comment]
Goal:
When someone fills out a webform and provides an email (or a phone)
If they already exist in D.T update the existing record instead of creating a new one.


How in D.T:
Add a flag when creating record for whether to check for dups and for what field

Hook into the start of the create record function to search for dups

if dup detected, then call the update instead of the create.

Comment and @mention the assigned to

IN webform plugin
Add a setting to looks for dups
Call the create with the correct flag.

**Comment by corsacca** [comment]
@kodinkat Add a setting to looks for dups
