### ISSUE TITLE
Preview Forbidden

### ISSUE THREAD

**Issue by olsonsp4c** [DiscipleTools/disciple-tools-webform#48]
Hello,

When trying to preview a form, we get a forbidden message at https://dtools.fidelisproject.com. Thoughts?

![image](https://user-images.githubusercontent.com/52258250/134245917-1018c78d-0bf0-4b27-ac25-68f30597091c.png)

Thank you for making this awesome software!

Scott

**Comment by corsacca** [comment]
Hey Scott. 
Sorry you are bumping in to issues.
I've tried a couple ways but i can't seem to replicate the issue.
Would you be willing to tell us more info on your setup?
The most helpful would be the contents of WP Admin > Utilities (D.T) page > Overview page that looks like this:
![image](https://user-images.githubusercontent.com/24901539/134310092-413a10a2-08ee-4a10-b1ab-4bcc7ceeea2c.png)

Does a new form show this too, or only after customizing it?

**Comment by olsonsp4c** [comment]
Unfortunately, I didn't create the form. However, I asked the person who
did and he says that it was a newly created form. Here are the pics!

[image: image.png]
[image: image.png]
[image: image.png]
Scott
equip4service.com <https://www.equip4service.com>

**Comment by corsacca** [comment]
Hey @olsonsp4c those images didn't come through.

**Comment by olsonsp4c** [comment]
Here you go! Attached this time

**Comment by corsacca** [comment]
@olsonsp4c you'll need to upload them directly to https://github.com/DiscipleTools/disciple-tools-webform/issues/48, not by email.

**Comment by olsonsp4c** [comment]
Here you go
![dtools1](https://user-images.githubusercontent.com/52258250/134713122-e04b3541-f769-4e09-a7ef-b0166e7e56f9.png)
![dtools2](https://user-images.githubusercontent.com/52258250/134713148-bc557ab5-7358-4f2f-882d-b59b43c571c9.png)
![dtools3](https://user-images.githubusercontent.com/52258250/134713162-d060f266-e176-44d0-b63b-ac72d065562c.png)

**Comment by corsacca** [comment]
This problem was due to a server configuration blocking direct file access.

**Comment by corsacca** [comment]
potential cause by the ithemes security plugin:
![image](https://user-images.githubusercontent.com/24901539/181916198-2562c03d-5dd5-4919-8707-080061b0cb7e.png)
