### ISSUE TITLE
Trying to Modify a Field. Pulling out my hair. 

### ISSUE THREAD

**Issue by soulascribe** [DiscipleTools/disciple-tools-webform#51]
I'm having a real challenge figuring out how to change / modify a field once I've created a custom one. It gives me the option to create a "Drop down", but I never get a place to fill out the custom answers. In my case, I'm making a progress drop-down to indicate which section of our training course the learner has completed (e.g. Section 1, Section 2, etc...) Here's the screen capture / video: https://youtu.be/YNBfJE-3VEc

**Comment by corsacca** [comment]
Hey @soulascribe ,
I can't see your video. It is private.
Here is where you add the field options for a custom dropdown:
![image](https://user-images.githubusercontent.com/24901539/144376749-4426cf70-1f79-4e14-a432-2e0ea2bdb3f9.png)

**Comment by soulascribe** [comment]
cool, I think I've got it now. Thanks.

**Comment by corsacca** [comment]
Great!
