### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by olsonsp4c** [DiscipleTools/disciple-tools-webform#55]
Would it be possible to create a way to delete a form created with this plug in? I've created a few forms, some of which are no longer needed. But, there is no way currently to delete forms. thanks!

Scott

**Comment by corsacca** [comment]
@olsonsp4c 
Does the "move to trash" option on the left work for you?
We recently made this work more consistently.
![image](https://user-images.githubusercontent.com/24901539/159277046-08b62174-ca1d-4619-94f4-69867ef24d88.png)

**Comment by corsacca** [comment]
Awesome! It might not have shown up when you submitted this question. Was working on some situations and not others.
