### ISSUE TITLE
Feature Request: Custom name for source

### ISSUE THREAD

**Issue by benmclure** [DiscipleTools/disciple-tools-webform#77]
Hi friends,

We have several sources/websites which go into one D.T. instance could there be an option in sources for custom names? For example if I get a contact from my website isaninheyati.com I'd like the source box in D.t. to indicate isaninheyati. Or if I get a contact from gercekisa.com I'd like to see the source be listed as gercekisa.

<img width="958" alt="Screenshot 2023-03-17 at 5 59 07 pm" src="https://user-images.githubusercontent.com/80407688/225956419-7600767d-ab16-4440-af51-ec5ac14006a2.png">

**Comment by corsacca** [comment]
@benmclure I'm not sure what the request is here. If you create the source in D.T, then you should be able to selected as a source in you weborm.
Or are you wanting to use the same webform on multiple websites?

**Comment by corsacca** [comment]
Here is the ability to set a custom source
In the shortcode
Or by adding `?source=source_key`. Replace source_key with the key of the source option.
See https://github.com/DiscipleTools/disciple-tools-webform/pull/86
