### ISSUE TITLE
Feature Enquiry: Support for datetime (calendar) dropdown field type

### ISSUE THREAD

**Issue by zipho** [DiscipleTools/disciple-tools-webform#96]
Hi All

I apologize in advance if the feature exists. My use case is to develop a form with date as one of the form elements.

What would be ideal, is to have it as both as a DT field or Other field element. 

A dropdown calendar with an option to even select the time as a stretch. 

Blessings

**Comment by corsacca** [comment]
Hey @zipho ,

You you can create a date field in D.T and then add that date field to the webform:
<img width="294" alt="image" src="https://github.com/DiscipleTools/disciple-tools-webform/assets/24901539/fb473589-899b-4ee4-9efa-cecf794740c0">

**Comment by zipho** [comment]
This needed me to relink the sites and only then now I can see the DT field on the list. Thanks @corsacca for confirmation.
