### ISSUE TITLE
Bug: Connection Type is Empty

### ISSUE THREAD

**Issue by zipho** [DiscipleTools/disciple-tools-webform#97]
Hi All

What could be causing the Connect Type on the site link form to be empty?

![CleanShot 2024-05-23 at 18 48 34@2x](https://github.com/DiscipleTools/disciple-tools-webform/assets/2108971/b11d549a-ae79-4d45-afc9-ca0204501534)

Any help will be appreciated on this.

**Comment by corsacca** [comment]
This is in setting up a site link.
@zipho the connection type starts empty and needs to be set on the site where the contacts are being sent to. This field can stay empty on the site you have the webform on.

See [site link documentation](https://disciple.tools/user-docs/getting-started-info/admin/site-links/)

Did you set it before and it is now empty againg?

**Comment by zipho** [comment]
Thanks for the response @corsacca. This is from the site with webform on. 

This is the second instance, and it's always empty. I guess it's the expected behaviour.

**Comment by corsacca** [comment]
THanks @zipho
